# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

r_github_packages:
 - jimhester/covr
 - jimhester/lintr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'lintr::lint_package()'
