# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - knitr
  - rmarkdown
  - covr
  - lintr
#  - DiagrammeRsvg
#  - rsvg
#  - V8

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  allow_failures:
    - r: oldrel

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
 - Rscript -e 'covr::coveralls()'
 - Rscript -e 'lintr::lint_package()'
